---
title: "EDA"
author: "Jae Yeon Kim"
date: "`r Sys.Date()`"
output: html_document
---

# Install pkgs and load data 

```{r}

if (!require(pacman)) install.packages("pacman")

pacman::p_load(glue, 
               here, 
               tidyverse,
               readxl,
               boot, 
               estimatr, 
               remotes,
               modelsummary,
               marginaleffects,
               mediation,
               lme4, 
               fixest, 
               glmnet, 
               naniar,
               patchwork)

install_github("vincentarelbundock/tinytable")
library(tinytable)

devtools::install_github("graemeblair/stdidx")
library(stdidx)

# Global ggplot2 theme
ggplot2::theme_set(theme_minimal())
```

```{r}
# Study 1 
df1 <- read_xlsx(here("raw_data", "Stress+Testing+Black-Latino+Coalition_December+8,+2023_18.48.xlsx"))[-c(1:2),] # skip the first two rows 

# Study 2
df2 <- read_csv(here("raw_data", "Stress+Testing+Black-Latino+Coalition+Replication_March+3,+2024_10.40.csv"))[-c(1:2),] # skip the first two rows 
```

# Attention checks

```{r}
df1_attn_count <- df1 %>%
  mutate(attention_check_passed = ifelse(AttentionCheck == 2, "Passed", "Failed")) %>%
  ggplot(aes(x = attention_check_passed)) + 
  geom_histogram(stat = "count") +
  labs(
    title = "Study 1",
    x = "Attention check status", 
    y = "Count")

df2_attn_count <- df2 %>%
  mutate(attention_check_passed = ifelse(AttentionCheck == 2, "Passed", "Failed")) %>%
  ggplot(aes(x = attention_check_passed)) + 
  geom_histogram(stat = "count") +
  labs(
    title = "Study 2",
    x = "Attention check status", 
    y = "Count")

png(filename = here("outputs", "attention_checks.png"),
    height = 8, 
    width = 10, 
    unit = "in", 
    res = 1200)

df1_attn_count + df2_attn_count + plot_annotation(tag_levels = "a")

dev.off()
```

# Descriptive statistics  

```{r}
df1_race_count <- df1 %>%
  mutate(race_cat = ifelse(Race == 2, "Black", "Others")) %>%
  ggplot(aes(x = race_cat)) + 
  geom_histogram(stat = "count") +
  labs(
    title = "Study 1",
    x = "Racial composition", 
    y = "Count")

df2_race_count <- df2 %>%
  mutate(race_cat = ifelse(Race == 2, "Black", "Others")) %>%
  ggplot(aes(x = race_cat)) + 
  geom_histogram(stat = "count") +
  labs(
    title = "Study 2",
    x = "Racial composition", 
    y = "Count")

png(filename = here("outputs", "racial_composition.png"),
    height = 8, 
    width = 10, 
    unit = "in", 
    res = 1200)

df1_race_count + df2_race_count + plot_annotation(tag_levels = "a")

dev.off()
```

```{r}
df1 <- df1 %>%
  mutate(Solidarity_Bond = as.numeric(Solidarity_Bond), 
         Solidarity_Allies = as.numeric(Solidarity_Allies), 
         Solidariy_CFate = as.numeric(Solidariy_CFate), 
         Latino_1 = as.numeric(Latino_1), 
         Latino_2R = as.numeric(Latino_2R), 
         Latino_3 = as.numeric(Latino_3), 
         Latino_4 = as.numeric(Latino_4)) %>%
  mutate(
    # Solidarity index
    sol_index = idx_mean(Solidarity_Bond, Solidarity_Allies, Solidariy_CFate), 
    # Latino support index
    latino_support_index = idx_mean(Latino_1, Latino_2R, Latino_3, Latino_4)
    )

df2 <- df2 %>%
  mutate(Solidarity_Bond = as.numeric(Solidarity_Bond), 
       Solidarity_Allies = as.numeric(Solidarity_Allies), 
       Solidariy_CFate = as.numeric(Solidariy_CFate), 
       Latino_1 = as.numeric(Latino_1), 
       Latino_2R = as.numeric(Latino_2R), 
       Latino_3 = as.numeric(Latino_3), 
       Latino_4 = as.numeric(Latino_4)) %>%
  mutate(
    # Solidarity index
    sol_index = idx_mean(Solidarity_Bond, Solidarity_Allies, Solidariy_CFate), 
    # Latino support index
    latino_support_index = idx_mean(Latino_1, Latino_2R, Latino_3, Latino_4)
    )
```

```{r}
df_med_mods <- bind_rows(
  df1 %>%
    dplyr::select(sol_index, latino_support_index, Control_Turtle, SharedDisc, Incommensurate) %>%
    mutate(study = "Study 1"),
  df2 %>%
    dplyr::select(sol_index, latino_support_index, Control_Turtle, SharedDisc, Incommensurate) %>%
    mutate(study = "Study 2") 
  ) %>%
  mutate(study = factor(study))
```

```{r}
df_med_mods <- df_med_mods %>%
  mutate(Condition = paste(Control_Turtle, SharedDisc, Incommensurate)) %>%
  filter(Condition != "NA NA NA") %>%
  replace_na(list(Control_Turtle = "0", 
             SharedDisc = "0", 
             Incommensurate = "0")) %>%
  mutate(Control_Turtle = as.numeric(Control_Turtle), 
         SharedDisc = as.numeric(SharedDisc), 
         Incommensurate = as.numeric(Incommensurate)) 

df_med_mods %>% 
  group_by(Control_Turtle, SharedDisc, Incommensurate) %>%
  count()
```

```{r}
df_med_mods %>%
  group_by(SharedDisc, Incommensurate, study) %>%
  summarize(
    estimate = mean(sol_index, na.rm = TRUE), 
    lower_ci = mean(sol_index, na.rm = TRUE) - qt(0.975, n() - 1) * sd(sol_index, na.rm = TRUE) / sqrt(n()), 
    upper_ci = mean(sol_index, na.rm = TRUE) + qt(0.975, n() - 1) * sd(sol_index, na.rm = TRUE) / sqrt(n())
  ) %>%
  ungroup() %>%
  mutate(assignment = rep(c("Control", "Incommensurate", "SharedDisc", "SharedDisc + Incommensurate"), each = 2)) %>%
  ggplot(aes(x = assignment, y = estimate, ymax = upper_ci, ymin = lower_ci, col = study)) +
  geom_pointrange() +
  labs(x = "", y = "POC solidarity index", 
       col = "Study")
```

```{r}
df_med_mods %>%
  group_by(SharedDisc, Incommensurate, study) %>%
  summarize(
    estimate = mean(latino_support_index, na.rm = TRUE), 
    lower_ci = mean(latino_support_index, na.rm = TRUE) - qt(0.975, n() - 1) * sd(sol_index, na.rm = TRUE) / sqrt(n()), 
    upper_ci = mean(latino_support_index, na.rm = TRUE) + qt(0.975, n() - 1) * sd(sol_index, na.rm = TRUE) / sqrt(n())
  ) %>%
  ungroup() %>%
  mutate(assignment = rep(c("Control", "Incommensurate", "SharedDisc", "SharedDisc + Incommensurate"), each = 2)) %>%
  ggplot(aes(x = assignment, y = estimate, ymax = upper_ci, ymin = lower_ci, col = study)) +
  geom_pointrange() +
  labs(x = "", y = "Latino support index",
       col = "Study")
```

# Causal mediation analysis 

```{r}
med.fit_sol <- lmer(Incommensurate ~ SharedDisc + (1|study), data = df_med_mods %>%
                filter(!is.na(sol_index)))

out.fit_sol <- lmer(sol_index ~ Incommensurate + SharedDisc + (1|study), data = df_med_mods)

out.fit_sol_intc <- lmer(sol_index ~ Incommensurate * SharedDisc + (1|study), data = df_med_mods)

med.out_sol <- mediate(med.fit_sol, out.fit_sol, treat = "SharedDisc", mediator = "Incommensurate", sims = 1000)

med.out_sol_intc <- mediate(med.fit_sol, out.fit_sol_intc, treat = "SharedDisc", mediator = "Incommensurate", sims = 1000)
```

```{r}
med.fit_latino <- lmer(Incommensurate ~ SharedDisc + (1|study), data = df_med_mods %>%
                filter(!is.na(latino_support_index)))

out.fit_latino <- lmer(latino_support_index ~ Incommensurate + SharedDisc + (1|study), data = df_med_mods)

out.fit_latino_intc <- lmer(latino_support_index ~ Incommensurate * SharedDisc + (1|study), data = df_med_mods)

med.out_latino <- mediate(med.fit_latino, out.fit_latino, treat = "SharedDisc", mediator = "Incommensurate", sims = 1000)

med.out_latino_intc <- mediate(med.fit_latino, out.fit_latino_intc, treat = "SharedDisc", mediator = "Incommensurate", sims = 1000)
```

```{r}
set.seed(1234)

# Treatment and mediator 
summary(med.out_sol)
summary(med.out_latino)

# Treatment and mediator interaction
summary(med.out_sol_intc)
summary(med.out_latino_intc)
```

# ATE estimation

```{r}
df1 <- df1 %>%
  mutate(Condition = paste(Control_Turtle, SharedDisc, Incommensurate)) %>%
  filter(Condition != "NA NA NA") %>%
  mutate(assignment_status = 
           case_when(
             Condition == "1 NA 1" ~ "Control + Incommensurate",
             Condition == "1 NA NA" ~ "Control",
             Condition == "NA 1 1" ~ "Shared Discrimination + Incommensurate",
             Condition == "NA 1 NA" ~ "Shared Discrimination"
           ))

df2 <- df2 %>%
  mutate(Condition = paste(Control_Turtle, SharedDisc, Incommensurate)) %>%
  filter(Condition != "NA NA NA") %>%
  mutate(assignment_status = 
           case_when(
             Condition == "1 NA 1" ~ "Control + Incommensurate",
             Condition == "1 NA NA" ~ "Control",
             Condition == "NA 1 1" ~ "Shared Discrimination + Incommensurate",
             Condition == "NA 1 NA" ~ "Shared Discrimination"
           ))
```

```{r}
df_mods <- bind_rows(
  df1 %>%
    dplyr::select(sol_index, latino_support_index, assignment_status) %>%
    mutate(study = "Study 1"),
  df2 %>%
    dplyr::select(sol_index, latino_support_index, assignment_status) %>%
    mutate(study = "Study2") 
  ) %>%
  mutate(study = factor(study))
```

```{r}
mods <- list(
  "POC solidarity index" = feols(sol_index ~ factor(assignment_status), data = df_mods, vcov = "hetero"),
  "POC solidarity index (with FE)" = feols(sol_index ~ factor(assignment_status) | study, data = df_mods, vcov = "hetero"), 
  "Latino support index" = feols(latino_support_index ~ factor(assignment_status), data = df_mods, vcov = "hetero"),
  "Latino support index (with FE)" = feols(latino_support_index ~ factor(assignment_status) | study, data = df_mods, vcov = "hetero")
)
```

```{r}
modelsummary(mods,
             estimate = c("{estimate}{stars} \n [{conf.low}, {conf.high}] \n p = {p.value}"),
             statistic = NULL,
             output = "gt"
             )
             #coef_map = mad_cm,
             #coef_omit = "Intercept"
#)
```